# src/main/resources/application.yml

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Hoặc validate, none, create tùy theo nhu cầu. 'update' tự động tạo/cập nhật bảng.
    show-sql: true # Hiển thị SQL trong logs (hữu ích khi debug)

server:
  port: 8080 # Mặc định của Spring Boot. Render sẽ ánh xạ cổng này.